# Generated by Django 5.2.16 on 2026-07-27 18:09

import django.db.models.deletion
from django.db import migrations, models


def backfill_link_sections(apps, schema_editor):
    InterviewEntityLink = apps.get_model("mentions", "InterviewEntityLink")
    TranscriptParagraph = apps.get_model("transcripts", "TranscriptParagraph")

    paragraph_sections = dict(
        TranscriptParagraph.objects.filter(
            entity_links__scope="paragraph",
            entity_links__section__isnull=True,
        ).values_list("pk", "section_id")
    )
    for paragraph_id, section_id in paragraph_sections.items():
        InterviewEntityLink.objects.filter(
            paragraph_id=paragraph_id,
            scope="paragraph",
            section__isnull=True,
        ).update(section_id=section_id)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('interviews', '0002_importrun_interview_medium_and_more'),
        ('mentions', '0001_initial'),
        ('transcripts', '0002_transcriptsection_alter_transcriptparagraph_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='interviewentitylink',
            name='link_scope_matches_paragraph',
        ),
        migrations.AddField(
            model_name='interviewentitylink',
            name='paragraph_content_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='interviewentitylink',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entity_links', to='transcripts.transcriptsection'),
        ),
        migrations.RunPython(backfill_link_sections, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='interviewentitylink',
            name='review_status',
            field=models.CharField(choices=[('suggested', 'Suggested'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('needs_review', 'Needs review')], default='suggested', max_length=12),
        ),
        migrations.AddConstraint(
            model_name='interviewentitylink',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('paragraph__isnull', True), ('scope', 'interview'), ('section__isnull', True)), models.Q(('paragraph__isnull', False), ('scope', 'paragraph'), ('section__isnull', False)), _connector='OR'), name='link_scope_matches_paragraph'),
        ),
        migrations.AddConstraint(
            model_name='interviewentitylink',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('end_offset__isnull', True), ('start_offset__isnull', True)), models.Q(('end_offset__gte', models.F('start_offset')), ('end_offset__isnull', False), ('start_offset__isnull', False)), _connector='OR'), name='link_offsets_are_consistent'),
        ),
    ]
