# Generated by Django 5.2.16 on 2026-08-04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mentions", "0002_remove_interviewentitylink_link_scope_matches_paragraph_and_more"),
        ("transcripts", "0002_transcriptsection_alter_transcriptparagraph_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewentitylink",
            name="excerpt_type",
            field=models.CharField(
                choices=[
                    ("qa", "Question and answer"),
                    ("paragraph", "Paragraph"),
                    ("needs_review", "Needs review"),
                ],
                default="paragraph",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="interviewentitylink",
            name="answer_paragraph",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answer_entity_links",
                to="transcripts.transcriptparagraph",
            ),
        ),
        migrations.AddField(
            model_name="interviewentitylink",
            name="question_paragraph",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question_entity_links",
                to="transcripts.transcriptparagraph",
            ),
        ),
    ]
