# Generated by Django 5.2.16 on 2026-07-27 18:09

import django.db.models.deletion
from django.db import migrations, models


def backfill_sections(apps, schema_editor):
    Transcript = apps.get_model("transcripts", "Transcript")
    TranscriptSection = apps.get_model("transcripts", "TranscriptSection")
    TranscriptParagraph = apps.get_model("transcripts", "TranscriptParagraph")

    for transcript in Transcript.objects.all().iterator():
        if not TranscriptParagraph.objects.filter(
            transcript_id=transcript.pk, section__isnull=True
        ).exists():
            continue
        section, _ = TranscriptSection.objects.get_or_create(
            transcript_id=transcript.pk,
            order=1,
            defaults={
                "heading": "Transcript",
                "level": 2,
                "section_type": "transcript",
                "publication_status": "private_only",
            },
        )
        TranscriptParagraph.objects.filter(
            transcript_id=transcript.pk, section__isnull=True
        ).update(section_id=section.pk)


class Migration(migrations.Migration):

    dependencies = [
        ('transcripts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('heading', models.CharField(max_length=255)),
                ('level', models.PositiveSmallIntegerField(default=2)),
                ('section_type', models.CharField(choices=[('notes', 'Notes'), ('audio', 'Audio'), ('transcript', 'Transcript'), ('sources', 'Sources'), ('tracklist', 'Tracklist'), ('video', 'Video'), ('other', 'Other')], default='other', max_length=16)),
                ('source_anchor', models.SlugField(blank=True, max_length=180)),
                ('publication_status', models.CharField(choices=[('metadata_only', 'Metadata only'), ('authorized_text', 'Authorized text'), ('pending_permission', 'Pending permission'), ('private_only', 'Private only')], default='private_only', max_length=24)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='transcriptparagraph',
            options={'ordering': ['section__order', 'order']},
        ),
        migrations.RemoveConstraint(
            model_name='transcriptparagraph',
            name='unique_transcript_paragraph_order',
        ),
        migrations.AddField(
            model_name='transcriptsection',
            name='transcript',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='transcripts.transcript'),
        ),
        migrations.AddField(
            model_name='transcriptparagraph',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='transcripts.transcriptsection'),
        ),
        migrations.RunPython(backfill_sections, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='transcriptparagraph',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='transcripts.transcriptsection'),
        ),
        migrations.AddConstraint(
            model_name='transcriptparagraph',
            constraint=models.UniqueConstraint(fields=('section', 'order'), name='unique_section_paragraph_order'),
        ),
        migrations.AddConstraint(
            model_name='transcriptsection',
            constraint=models.UniqueConstraint(fields=('transcript', 'order'), name='unique_transcript_section_order'),
        ),
    ]
