# Generated by Django 5.2.16 on 2026-08-08

import django.db.models.deletion
import apps.transcripts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transcripts", "0002_transcriptsection_alter_transcriptparagraph_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transcript",
            name="language",
            field=models.CharField(
                default="en",
                help_text="Original transcript language as an ISO/BCP-47 code.",
                max_length=12,
                validators=[apps.transcripts.models.validate_language_code],
            ),
        ),
        migrations.CreateModel(
            name="TranscriptTranslation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("target_language", models.CharField(max_length=12, validators=[apps.transcripts.models.validate_language_code])),
                ("provider", models.CharField(default="deepl", max_length=32)),
                ("status", models.CharField(choices=[("available", "Available")], default="available", max_length=16)),
                ("translated_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("transcript", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="translations", to="transcripts.transcript")),
            ],
            options={"ordering": ["target_language"]},
        ),
        migrations.CreateModel(
            name="TranscriptTranslationRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("target_language", models.CharField(max_length=12, validators=[apps.transcripts.models.validate_language_code])),
                ("status", models.CharField(choices=[("queued", "Queued"), ("processing", "Processing"), ("completed", "Completed"), ("failed", "Failed")], default="queued", max_length=16)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("transcript", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="translation_requests", to="transcripts.transcript")),
            ],
            options={"ordering": ["requested_at", "id"]},
        ),
        migrations.CreateModel(
            name="TranscriptTranslationSection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveIntegerField()),
                ("heading", models.CharField(max_length=255)),
                ("level", models.PositiveSmallIntegerField(default=2)),
                ("section_type", models.CharField(choices=[("notes", "Notes"), ("audio", "Audio"), ("transcript", "Transcript"), ("sources", "Sources"), ("tracklist", "Tracklist"), ("video", "Video"), ("other", "Other")], default="other", max_length=16)),
                ("source_anchor", models.SlugField(blank=True, max_length=180)),
                ("source_section", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="transcripts.transcriptsection")),
                ("translation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sections", to="transcripts.transcripttranslation")),
            ],
            options={"ordering": ["order"]},
        ),
        migrations.CreateModel(
            name="TranscriptTranslationParagraph",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveIntegerField()),
                ("speaker", models.CharField(blank=True, max_length=160)),
                ("text", models.TextField()),
                ("start_seconds", models.PositiveIntegerField(blank=True, null=True)),
                ("end_seconds", models.PositiveIntegerField(blank=True, null=True)),
                ("section", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="paragraphs", to="transcripts.transcripttranslationsection")),
                ("source_paragraph", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="transcripts.transcriptparagraph")),
                ("translation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="paragraphs", to="transcripts.transcripttranslation")),
            ],
            options={"ordering": ["section__order", "order"]},
        ),
        migrations.AddConstraint(
            model_name="transcripttranslation",
            constraint=models.UniqueConstraint(fields=("transcript", "target_language"), name="unique_transcript_translation_language"),
        ),
        migrations.AddConstraint(
            model_name="transcripttranslationrequest",
            constraint=models.UniqueConstraint(fields=("transcript", "target_language"), name="unique_translation_request_language"),
        ),
        migrations.AddConstraint(
            model_name="transcripttranslationsection",
            constraint=models.UniqueConstraint(fields=("translation", "order"), name="unique_translation_section_order"),
        ),
        migrations.AddConstraint(
            model_name="transcripttranslationsection",
            constraint=models.UniqueConstraint(fields=("translation", "source_section"), name="unique_translation_source_section"),
        ),
        migrations.AddConstraint(
            model_name="transcripttranslationparagraph",
            constraint=models.UniqueConstraint(fields=("section", "order"), name="unique_translation_paragraph_order"),
        ),
        migrations.AddConstraint(
            model_name="transcripttranslationparagraph",
            constraint=models.UniqueConstraint(fields=("translation", "source_paragraph"), name="unique_translation_source_paragraph"),
        ),
    ]
