# Generated by Django 5.2.16 on 2026-08-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="is_b_side",
            field=models.BooleanField(default=False),
        ),
    ]
