# Generated by Django 5.2.16 on 2026-07-27 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(default='DM Live Wiki', max_length=120)),
                ('input_format', models.CharField(choices=[('xml', 'XML'), ('json', 'JSON')], max_length=8)),
                ('input_name', models.CharField(max_length=500)),
                ('input_sha256', models.CharField(blank=True, max_length=64)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='running', max_length=12)),
                ('pages_seen', models.PositiveIntegerField(default=0)),
                ('pages_created', models.PositiveIntegerField(default=0)),
                ('pages_updated', models.PositiveIntegerField(default=0)),
                ('pages_skipped', models.PositiveIntegerField(default=0)),
                ('pages_failed', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='interview',
            name='medium',
            field=models.CharField(choices=[('radio', 'Radio'), ('television', 'Television'), ('magazine', 'Magazine'), ('newspaper', 'Newspaper'), ('online', 'Online'), ('press_conference', 'Press conference'), ('other', 'Other'), ('unknown', 'Unknown')], default='unknown', max_length=24),
        ),
        migrations.AddField(
            model_name='interview',
            name='source_content_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='interview',
            name='source_domain',
            field=models.CharField(default='dmlive.wiki', max_length=120),
        ),
        migrations.AddField(
            model_name='interview',
            name='source_name',
            field=models.CharField(default='DM Live Wiki', max_length=120),
        ),
        migrations.AddField(
            model_name='interview',
            name='source_page_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='source_present',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='source_revision_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='source_revision_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sourcesnapshot',
            name='revision_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sourcesnapshot',
            name='source_page_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sourcesnapshot',
            name='source_present',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sourcesnapshot',
            name='source_revision_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sourcesnapshot',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('not_modified', 'Not modified'), ('error', 'Error'), ('blocked', 'Blocked'), ('missing', 'Missing')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['source_present', 'source_domain'], name='interview_source_state_idx'),
        ),
        migrations.AddField(
            model_name='sourcesnapshot',
            name='import_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_snapshots', to='interviews.importrun'),
        ),
    ]
