# Generated by Django 5.2.16 on 2026-07-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_importrun_interview_medium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='classification_status',
            field=models.CharField(choices=[('interview', 'Interview'), ('needs_review', 'Needs review'), ('not_interview', 'Not an interview')], default='interview', max_length=16),
        ),
        migrations.AddField(
            model_name='sourcesnapshot',
            name='snapshot_path',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['classification_status'], name='interview_classification_idx'),
        ),
    ]
