# Generated by Django 5.2.16 on 2026-08-05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("interviews", "0003_interview_classification_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InterviewMentionReview",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("pending", "Pending"), ("in_review", "In review"), ("reviewed_with_links", "Reviewed with links"), ("reviewed_without_song", "Reviewed without song")], default="pending", max_length=24)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("interview", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="mention_review", to="interviews.interview")),
                ("reviewer", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="interview_mention_reviews", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name="interviewmentionreview",
            index=models.Index(fields=["status"], name="interview_mention_review_idx"),
        ),
    ]
